/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.uk;

public class App {
    public String getGreeting() {
        Library library = new Library();
        library.someLibraryMethod();
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
